server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: zuul-zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1111/eureka,http://localhost:2222/eureka
zuul:
  routes:
    order-provider:
      path: /p-order/**      
              
